ersion: 0.0
os: windows
files:
  - source: /
    destination: c:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: scripts/before_install.bat
      timeout: 900
  AfterInstall:
    - location: scripts/after_install.bat
      timeout: 900