version: 0.2

phases:
  install:
    commands:
      - echo No dependencies to install
  build:
    commands:
      - echo Build phase not required for a simple static site
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes
