version: 0.2

phases:
  build:
    commands:
      - echo "Running updateSongInfo function"
      - echo "<html><head><script src='script.js'></script></head><body><script>function updateSongInfo() {
          console.log('Function updateSongInfo() executed successfully');
        }
        updateSongInfo();</script></body></html>" > index.html

artifacts:
  files:
    - index.html   # Incluye el archivo index.html generado en el artefacto
  discard-paths: yes


