version: 0.2

phases:
  build:
    commands:
      - echo "Running build phase"
      - type index.html

  post_build:
    commands:
      - echo "Running test phase"
      - |
        if (Select-String -Path index.html -Pattern '<script src="script.js"></script>' -Quiet) {
          echo "script.js is correctly referenced in index.html"
        } else {
          echo "Error: script.js is not correctly referenced in index.html"
          exit 1
        }
      - |
        if (Select-String -Path index.html -Pattern '<link rel="stylesheet" href="style.css">' -Quiet) {
          echo "style.css is correctly referenced in index.html"
        } else {
          echo "Error: style.css is not correctly referenced in index.html"
          exit 1
        }

artifacts:
  files:
    - index.html
  discard-paths: yes
