version: 0.2

phases:
  build:
    commands:
      - echo "Running build phase"
      - type index.html

  post_build:
    commands:
      - echo "Running test phase"
      - |
        $errors = @()
        
        if (-not (Test-Path -Path "Images/image9.png")) {
          $errors += "Error: Images/image1.png not found"
        }
        
        if (-not (Test-Path -Path "songs/Song4.mp3")) {
          $errors += "Error: songs/Song4.mp3 not found"
        }
        
        if ($errors.Count -gt 0) {
          echo "Errors found:"
          $errors | ForEach-Object { echo $_ }
          exit 1
        } else {
          echo "All checks passed successfully"
        }

artifacts:
  files:
    - '**/*'
  discard-paths: no
