version: 0.2

phases:
  build:
    commands:
      - echo "Running updateSongInfo function"
      - echo "<html><head><script src='script.js'></script></head><body><script>function updateSongInfo() {
          var songs = [{title: 'Song Title', name: 'Artist Name', source: 'song.mp3'}]; // Sample data
          var currentSongIndex = 0;
          var songName = document.getElementById('songName');
          var artistName = document.getElementById('artistName');
          var song = new Audio();
          var progress = document.getElementById('progress');

          songName.textContent = songs[currentSongIndex].title;
          artistName.textContent = songs[currentSongIndex].name;
          song.src = songs[currentSongIndex].source;

          song.addEventListener('loadeddata', function() {
            console.log('Song data loaded');
          });

          song.addEventListener('timeupdate', function() {
            if (!song.paused) {
              progress.value = song.currentTime;
            }
          });

          song.addEventListener('loadedmetadata', function() {
            progress.max = song.duration;
            progress.value = song.currentTime;
            console.log('Metadata loaded');
          });
        }
        updateSongInfo();</script></body></html>" > index.html

artifacts:
  files:
    - index.html   # Incluye el archivo index.html generado en el artefacto
  discard-paths: yes

